<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.20" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KFCMenuAPI.BLL\KFCMenuAPI.BLL.csproj" />
    <ProjectReference Include="..\KFCMenuAPI.DAL\KFCMenuAPI.DAL.csproj" />
    <ProjectReference Include="..\KFCMenuAPI.Model\KFCMenuAPI.Model.csproj" />
  </ItemGroup>

</Project>
